### ISSUE TITLE
[FEAT] : User suggestions block.

### ISSUE THREAD

**Issue by anglerfishlyy** [Commu-net/Mailer_frontend#17]
Description : Let's enhance Communet-Extension with User suggestions block! This feature will let users to suggest /give ideas about the improvements of communet website. It's all about making our experience smoother and more enjoyable.

Proposed Implementation:
1.Develop a block where input could be given by the user.
2.Make that part as a suggestion box that could give us new ideas from the customers/users of the website.
3.Save all the inputs given by users and store the data.

Afterwards , we , The developers need to take out insightful ideas from users and should work on it.

If you have any ideas please mention them in the comments . lets add it up.

Can't wait to hear your thoughts! Give us a thumbs up 👍 if you're excited about this addition!

Together, let's make Communet-Extension awesome! 🚀

**Comment by rituraj12797** [comment]
@anglerfishlyy  You can go for it, the idea seems cool, also improve the Ui for the extension to make it a bit more familiar with the frontend 
refer here : https://commu-net.vercel.app/

**Comment by anglerfishlyy** [comment]
Alright.

**Comment by anglerfishlyy** [comment]
I am working on it . I hope you will label it's level and  GSSOC'24 tag/label.

**Comment by anglerfishlyy** [comment]
shall i close it?
